backend:
  name: taskflow-backend
  replicaCount: 1
  image:
    repository: 499193102935.dkr.ecr.us-east-1.amazonaws.com/taskflow-backend
    tag: "1.0"
    pullPolicy: IfNotPresent
  containerPort: 5001
  service:
    name: taskflow-backend-service
    type: ClusterIP
    port: 5001
    targetPort: 5001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

frontend:
  name: taskflow-frontend
  replicaCount: 1
  image:
    repository: 499193102935.dkr.ecr.us-east-1.amazonaws.com/taskflow-frontend
    tag: "1.0"
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    name: taskflow-frontend-service
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"

configMap:
  name: taskflow-config
  data:
    NODE_ENV: "production"
    PORT: "5001"
    DB_USER: "taskflow_user"
    DB_NAME: "taskflow"
    DB_HOST: "taskflow.cm7mwco6y04o.us-east-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_SSL: "true"

secret:
  name: taskflow-secret
  data:
    DB_PASSWORD: "taskflowuser123"
    JWT_SECRET: "ab140d6a37f77fa759639ab6feefdf4226ab8c6672adbd01bee28fecef2a4af7"