# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  PORT: "5001"
  DB_USER: "taskflow_user"
  DB_NAME: "taskflow"
  DB_HOST: "taskflow.crmeaegqqncj.us-east-1.rds.amazonaws.com"  # ← RDS endpoint!
  DB_PORT: "5432"
  DB_SSL: "true"
  NODE_ENV: "production"
  CLIENT_URL: "http://zaneapp.mohicanstech.com"  # ← frontend URL for CORS and email links
