apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
type: Opaque
stringData:
  DB_PASSWORD: taskflowuserstrongpassword
  JWT_SECRET: 56adf552a639de170b4ac63fc2561c8a2cb65275ca8735402c86bff06aadfdb4
