apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
type: Opaque
stringData:
  DB_PASSWORD: taskflowuser123
  JWT_SECRET: ab140d6a37f77fa759639ab6feefdf4226ab8c6672adbd01bee28fecef2a4af7
